version: appveyor.{build}
clone_folder: c:\dev\wearables
clone_depth: 1

platform: x64
configuration: Release

image:
  - Visual Studio 2015
  - Visual Studio 2017

skip_tags: true
skip_branch_with_pr: true

build:
  parallel: true
  verbosity: detailed

matrix:
  fast_finish: true

pull_requests:
  do_not_increment_build_number: true

init:
  - ps: $YARP_LATEST = "2.3.72"
  - ps: $ICUB_LATEST = "1.10.0"
  - ps: $ROBOTOLOGY_VS = "v14"
  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2015') { $GENERATOR = "Visual Studio 14 2015 Win64" }
  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2017') { $GENERATOR = "Visual Studio 15 2017 Win64" }

install:
  - ps: Start-FileDownload https://github.com/robotology/yarp/releases/download/v${YARP_LATEST}/yarp_${YARP_LATEST}_${ROBOTOLOGY_VS}_x86_amd64_1.exe -FileName c:\dev\yarp.exe -Timeout 300000
  #- ps: Start-FileDownload https://github.com/robotology/icub-main/releases/download/v${ICUB_LATEST}/iCub_${ICUB_LATEST}_${ROBOTOLOGY_VS}_x86_amd64_1.exe -FileName c:\dev\icub.exe -Timeout 300000
  - ps: Start-Process -FilePath "c:\dev\yarp.exe" -ArgumentList "/S" -Wait -NoNewWindow -PassThru
  #- ps: Start-Process -FilePath "c:\dev\icub.exe" -ArgumentList "/S" -Wait -NoNewWindow -PassThru

  - ps: |
      # From: https://www.michaelmiklis.de/update-environment-variables-in-current-process/
      # Modified to append appveyor's path
      $ENV_MACHINE = ([Environment]::GetEnvironmentVariables('Machine'))
      foreach ($EnvVar in $ENV_MACHINE.keys) {
        Set-Item "Env:$($EnvVar)" -Value $ENV_MACHINE[$EnvVar]
      }
      $ENV_USER = ([Environment]::GetEnvironmentVariables('User'))
      foreach ($EnvVar in $ENV_USER.keys) {
        if ($EnvVar -ne 'Path') {
          Set-Item "Env:$($EnvVar)" -Value $ENV_USER[$EnvVar]
        }
      }
      if ($ENV_USER.ContainsKey('Path')) {
        Set-Item Env:Path -Value ((($env:Path -split ";") + ($ENV_USER.Path -split ";") + ($ENV_MACHINE.Path -split ";") | select -Unique) -join ";")
      }

  - ps: git clone -q --depth 1 https://github.com/robotology/icub-firmware-shared.git c:\dev\icub-firmware-shared
  - ps: cd c:\dev\icub-firmware-shared
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -G"$GENERATOR" ..
  - ps: $env:icub_firmware_shared_DIR="c:\dev\icub-firmware-shared"

  - ps: git clone -q --depth 1 https://github.com/robotology/icub-main.git c:\dev\icub-main
  - ps: cd c:\dev\icub-main
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -G"$GENERATOR" ..
  - ps: cmake --build . --config $env:CONFIGURATION --target INSTALL

build_script:
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -G"$GENERATOR" ..
  - ps: cmake --build . --config $env:CONFIGURATION
